### ISSUE TITLE
Error when calling `craft.modules` when using `setComponents` method in PHP module

### ISSUE THREAD

**Issue by aaronbushnell** [timkelty/twig-tips#1]
First off, these are **excellent** and I didn't know about so much of this!

I've got a simple module here:
```php
<?php
namespace modules\appmodule;

class AppModule extends \yii\base\Module
{
    public function init()
    {
        parent::init();

        $this->setComponents([
            'collection' => \Illuminate\Support\Collection::class,
        ]);
    }
}
```

But calling...
```twig
{% dd craft.modules.appmodule.collect([ 1, 3, 5 ]).avg() %}
```

throws a Twig Runtime Error noting the following:
```
Twig Runtime Error – Twig\Error\RuntimeError
Calling unknown method: craft\web\twig\variables\CraftVariable::modules()
```

Has Craft changed the syntax on invoking these component classes directly via Twig?

**Comment by timkelty** [comment]
@aaronbushnell my bad, I missed `.app` in the example – should be: `craft.app.modules.appmodule`.

Your example should then be:

```
{% dd craft.app.modules.appmodule.collection.collect([ 1, 3, 5 ]).avg() %}
```

**Comment by aaronbushnell** [comment]
Thanks, @timkelty! It _seems_ like I'm unable to pass data from the Twig template into this PHP component class. Here's what I have:

```twig
{% dd craft.app.modules['my-module'].collection.collect([1, 2, 3]) %}
```

But my collection is empty. I feel like I'm probably missing something super obvious.

**Comment by timkelty** [comment]
@aaronbushnell actually, you need to use `make` as that is the static method that creates an instance of Collection:

```
{% dd craft.app.modules['my-module'].collection.make([1, 2, 3]) %}
```

**Comment by aaronbushnell** [comment]
Super late here, but that did it @timkelty! Thanks!
